### ISSUE TITLE
Scrolly in mobile

### ISSUE THREAD

**Issue by usamabilal** [Drexel-UHC/salurbal-city-selection-scrolly#3]
A couple issues in mobile (probably related) with chrome in iOS 
- [x] When scrolling sometimes the map pans instead of scrolling. Maybe we can disable panning? I don't think we need it
- [x] See image. Scrolling up and down foxes it ![image](https://github.com/Drexel-UHC/salurbal-city-selection-scrolly/assets/7773408/a4b8004d-f155-4889-9b25-aacd6e37c0ec)

**Comment by ran-codes** [comment]
made some updates (seee comment above). It looks okay to me on real phone now. btw do you know how to hard refresh on iphoen safair? (i had to to delete history for the cookies/githubpages to update).



Lmk what you think and feel free to close if its okay to you on phone.

**Comment by usamabilal** [comment]
Can we keep panning on the first map? the one with all the cities. Otherwise people can zoom but not move. Given its small size, people can scroll "around it" when going down (as opposed to the Sao Paulo example which take over the full screen).
Other than that perfect!

**Comment by ran-codes** [comment]
thanks! updated and deployed.
